import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
 
const myFont = localFont({
  src: '../public/font/clash.woff2',
})


export const metadata: Metadata = {
  title: "Vikram's Dev Portfolilo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={`${myFont.className}`}>
          {children}
      </body>
    </html>
  );
}
